// <auto-generated />
namespace IPNuty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Zmiana_Id_singera_w_rejestracji : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zmiana_Id_singera_w_rejestracji));
        
        string IMigrationMetadata.Id
        {
            get { return "201707141626503_Zmiana_Id_singera_w_rejestracji"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
